kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: train-schedule-image
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-schedule-image
  template:
    metadata:
      labels:
        app: train-schedule-image
    spec:
      containers:
      - name: train-schedule-image
        image: linuxacademycontent/train-schedule:1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: train-schedule-image
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: train-schedule-deployment
  minReplicas: 1
  maxReplicas: 74
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30
