kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: train-schedule-image
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule-image
spec:
  replicas: 4
  selector:
    matchLabels:
      app: train-schedule-image
  template:
    metadata:
      labels:
        app: train-schedule-image
    spec:
      containers:
      - name: train-schedule-image
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
